[package]
name = "ShelterZoneRustCert"
version = "1.0.0"
authors = ["harry"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.12.3"
serde_json = "1.0.56"
sha1 = "0.6.0"
